Repository CS2103JAN2018-F09-B3/main, pull requests merged in 2018-04, with the labels that each got.

#108 Add `buy` command related tests
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/model/CoinBook.java
  src/main/java/seedu/address/model/coin/Coin.java
  src/main/java/seedu/address/model/coin/Price.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/coin/CoinTest.java
Labels: type.task

#116 v1.4 Documentation
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EventHandling.uml
  docs/diagrams/FindCommandSequence.txt
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/ParserUtilSequence.txt
  docs/images/FindCommandSequence.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserUtilSequence.png
  docs/images/Ui.png
  docs/stylesheets/pdf-theme.yml
Labels: priority.high, type.task

#141 [#146] TokenType.java: Refactor prefix token type names.
  collated/functional/ewaldhew.md
  collated/test/Eldon-Chung.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BuyCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SellCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/BuyCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SellCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TokenType.java
  src/main/java/seedu/address/model/coin/Code.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/conditionalparser/SyntaxParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/testutil/CoinUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/TagCommandSystemTest.java
Labels: type.refactoring, type.task

#138 [#146] Coin.java: Refactor get profit, worth and profitability to return Amount
  src/main/java/seedu/address/model/coin/Amount.java
  src/main/java/seedu/address/model/coin/Coin.java
Labels: type.refactoring

#147 [#146] CoinBook: Refactor all instances of Address to Coin
  collated/functional/laichengyu.md
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/XmlRuleBookStorage.java
  src/main/java/seedu/address/storage/XmlSerializableCoinBook.java
  src/main/java/seedu/address/storage/XmlSerializableRuleBook.java
  src/main/java/seedu/address/ui/CoinCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/data/XmlCoinBookStorageTest/NotXmlFormatCoinBook.xml
  src/test/data/XmlCoinBookStorageTest/invalidAndValidCoinCoinBook.xml
  src/test/data/XmlCoinBookStorageTest/invalidCoinCoinBook.xml
  src/test/data/XmlSerializableCoinBookTest/invalidCoinCoinBook.xml
  src/test/data/XmlSerializableCoinBookTest/invalidTagCoinBook.xml
  src/test/data/XmlSerializableCoinBookTest/typicalCoinsCoinBook.xml
  src/test/data/XmlUtilTest/tempCoinBook.xml
  src/test/data/XmlUtilTest/validCoinBook.xml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTargetTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/model/CoinBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlCoinBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableCoinBookTest.java
  src/test/java/seedu/address/testutil/CoinBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalCoins.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/CoinBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/TagCommandSystemTest.java
Labels: type.refactoring

#179 [#46] Add condition generator
  collated/test/Eldon-Chung.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/conditions/AmountHeldCondition.java
  src/main/java/seedu/address/logic/conditions/CodeCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsBoughtCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsSoldCondition.java
  src/main/java/seedu/address/logic/conditions/MadeCondition.java
  src/main/java/seedu/address/logic/conditions/PriceCondition.java
  src/main/java/seedu/address/logic/conditions/TagCondition.java
  src/main/java/seedu/address/logic/conditions/WorthCondition.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ConditionGenerator.java
  src/main/java/seedu/address/logic/parser/ConditionSemanticParser.java
  src/main/java/seedu/address/logic/parser/ConditionSyntaxParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TokenType.java
  src/main/java/seedu/address/model/coin/Coin.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/conditionalparser/SyntaxParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
  src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
  src/test/java/seedu/address/logic/parser/ConditionSemanticParserTest.java
  src/test/java/seedu/address/logic/parser/ConditionSyntaxParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TokenStackTest.java
  src/test/java/seedu/address/testutil/CoinBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: category.Search, type.epic

#182 [#181] Tag: Revise TAG_VALIDATION_REGEX to only allow single worded tag names
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.task

#189 [#188] Refactor code condition
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/conditions/CodeCondition.java
  src/main/java/seedu/address/logic/parser/ConditionGenerator.java
  src/main/java/seedu/address/model/coin/Code.java
Labels: category.Search

#185 [#184] Coin.java: Revise equals method to only check Code attribute
  src/main/java/seedu/address/model/coin/Coin.java
Labels: category.Fix, type.bug

#183 [#152] Fix: Add getSourceIndex method in toIndex method in CommandTarget class
  src/main/java/seedu/address/logic/commands/CommandTarget.java
Labels: category.Fix, type.bug

#193 Fix bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BuyCommand.java
  src/main/java/seedu/address/logic/commands/NotifyCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SellCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CoinBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TokenType.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/testutil/CoinUtil.java
  src/test/java/systemtests/CoinBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ViewCommandSystemTest.java
Labels: category.Fix

#195 [#194] Add amount condition superclass
  src/main/java/seedu/address/logic/conditions/AmountCondition.java
  src/main/java/seedu/address/logic/conditions/AmountHeldCondition.java
  src/main/java/seedu/address/logic/conditions/CurrentPriceCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsBoughtCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsSoldCondition.java
  src/main/java/seedu/address/logic/conditions/MadeCondition.java
  src/main/java/seedu/address/logic/conditions/WorthCondition.java
  src/main/java/seedu/address/logic/parser/ConditionGenerator.java
Labels: type.refactoring

#199 [#109] Coin Amounts fixes
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/BuyCommand.java
  src/main/java/seedu/address/logic/commands/SellCommand.java
  src/main/java/seedu/address/logic/conditions/CurrentPriceCondition.java
  src/main/java/seedu/address/logic/parser/BuyCommandParser.java
  src/main/java/seedu/address/logic/parser/ConditionGenerator.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SellCommandParser.java
  src/main/java/seedu/address/model/CoinBook.java
  src/main/java/seedu/address/model/coin/Amount.java
  src/main/java/seedu/address/model/coin/Coin.java
  src/main/java/seedu/address/model/coin/Price.java
  src/main/java/seedu/address/storage/XmlAdaptedCoin.java
  src/main/java/seedu/address/ui/CoinCard.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/BuyCommandTest.java
  src/test/java/seedu/address/logic/parser/BuyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CoinBookParserTest.java
  src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/coin/CoinTest.java
  src/test/java/seedu/address/testutil/CoinBuilder.java
Labels: category.Fix, type.bug, type.task

#200 [#196] ParserUtil: Add warning logging for when Find argument parsing fails
  src/main/java/seedu/address/commons/core/CoinSubredditList.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: status.Done, type.refactoring

#202 [#167] Refactor tests
  src/main/java/seedu/address/logic/conditions/CodeCondition.java
  src/test/data/XmlSerializableCoinBookTest/invalidTagCoinBook.xml
  src/test/data/XmlSerializableCoinBookTest/typicalCoinsCoinBook.xml
  src/test/data/XmlUtilTest/invalidCoinField.xml
  src/test/data/XmlUtilTest/missingCoinField.xml
  src/test/data/XmlUtilTest/tempCoinBook.xml
  src/test/data/XmlUtilTest/validCoin.xml
  src/test/data/XmlUtilTest/validCoinBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/logic/commands/BuyCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTargetTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCoinDescriptorTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/model/CoinBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/coin/CodeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedCoinTest.java
  src/test/java/seedu/address/storage/XmlCoinBookStorageTest.java
  src/test/java/seedu/address/testutil/CoinBuilder.java
  src/test/java/seedu/address/testutil/TypicalCoins.java
  src/test/java/seedu/address/testutil/TypicalRules.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/CoinBookSystemTest.java
  src/test/java/systemtests/TagCommandSystemTest.java
  src/test/java/systemtests/ViewCommandSystemTest.java
Labels: status.Done, type.refactoring

#204 [#203] Rename address to coin in all commands, parameter names, and scripts
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UsingGradle.adoc
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/storage/XmlRuleBookStorage.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: type.refactoring

#206 Deal with unused files
  src/main/java/seedu/address/model/CryptoCompareHistoHourObject.java
  src/main/java/seedu/address/ui/MainWindow.java
  unused/NewsCard.java
  unused/NewsCardClickedEvent.java
  unused/NewsListCard.fxml
  unused/NewsListPanel.fxml
  unused/NewsListPanel.java
Labels: priority.normal

#187 D2 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/EventHandling.adoc
  docs/diagrams/EventHandling.uml
  docs/diagrams/FindActivityDiagram.txt
  docs/diagrams/FindCommandSequence.txt
  docs/diagrams/Lexer.uml
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/NotificationsSequenceDiagram1.adoc
  docs/diagrams/NotificationsSequenceDiagram1.uml
  docs/diagrams/NotificationsSequenceDiagram2.adoc
  docs/diagrams/NotificationsSequenceDiagram2.uml
  docs/diagrams/SDDelete.adoc
  docs/diagrams/SDDelete.uml
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StackDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StackDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStackDiagram.pptx
  docs/images/DeletePersonSdForLogic.png
  docs/images/FindActivityDiagram.png
  docs/images/FindCommandSequence.png
  docs/images/Lexer.png
  docs/images/LogicClassDiagram.png
  docs/images/NotificationsSequenceDiagram1.png
  docs/images/NotificationsSequenceDiagram2.png
  docs/images/RunningTests.png
  docs/images/SDforDeleteCoin.png
  docs/images/SDforDeletePersonEventHandling.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoExecuteUndoStackDiagram.png
  docs/images/UndoRedoNewCommand1StackDiagram.png
  docs/images/UndoRedoNewCommand2StackDiagram.png
  docs/images/UndoRedoNewCommand3StackDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStackDiagram.png
  docs/stylesheets/pdf-theme.yml
Labels: type.task

#215 [#214] SampleDataUtil: Change Coin names to actual Coin names
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.refactoring

#217 [#216] SyncCommand: Refactor toString to getAsString during Price construction
  src/main/java/seedu/address/logic/commands/SyncCommand.java
Labels: category.Fix

#228 MainApp: Fix rulebook init
  src/main/java/seedu/address/MainApp.java
Labels: category.Fix, type.bug

#232 [#223] Notifications jump to coin
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ShowNotificationRequestEvent.java
  src/main/java/seedu/address/logic/RuleChecker.java
  src/main/java/seedu/address/logic/commands/ActionCommand.java
  src/main/java/seedu/address/logic/commands/NotifyCommand.java
  src/main/java/seedu/address/logic/commands/SpawnNotificationCommand.java
  src/main/java/seedu/address/model/rule/NotificationRule.java
  src/main/java/seedu/address/model/rule/Rule.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: category.Sync, type.task

#229 NotifyCommand: Fix amount change condition matching
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TokenType.java
  src/main/java/seedu/address/model/coin/Coin.java
  src/main/java/seedu/address/model/coin/Price.java
Labels: category.Fix, type.bug

#230 [#225] Sync data on app startup
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/CoinCard.java
  src/test/java/seedu/address/TestApp.java
Labels: category.UX, type.task

#240 Fix Rule Actions
  src/main/java/seedu/address/commons/events/model/CoinChangedEvent.java
  src/main/java/seedu/address/logic/RuleChecker.java
  src/main/java/seedu/address/logic/commands/ActionCommand.java
  src/main/java/seedu/address/logic/commands/NotifyCommand.java
  src/main/java/seedu/address/logic/commands/SpawnNotificationCommand.java
  src/main/java/seedu/address/model/CoinBook.java
  src/main/java/seedu/address/model/coin/UniqueCoinList.java
Labels: category.Fix, type.bug

#243 Notifications: Add tests
  src/main/java/seedu/address/logic/commands/NotifyCommand.java
  src/main/java/seedu/address/model/coin/Amount.java
  src/main/java/seedu/address/storage/XmlAdaptedRule.java
  src/test/data/XmlRuleBookStorageTest/NotXmlFormatRuleBook.xml
  src/test/data/XmlRuleBookStorageTest/invalidAndValidRuleRuleBook.xml
  src/test/data/XmlRuleBookStorageTest/invalidRuleRuleBook.xml
  src/test/java/guitests/guihandles/RuleListPanelHandle.java
  src/test/java/seedu/address/logic/RuleCheckerTest.java
  src/test/java/seedu/address/logic/commands/ListNotifsCommandTest.java
  src/test/java/seedu/address/logic/commands/NotifyCommandTest.java
  src/test/java/seedu/address/logic/commands/SpawnNotificationCommandTest.java
  src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
  src/test/java/seedu/address/logic/parser/NotifyCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedRuleTest.java
  src/test/java/seedu/address/storage/XmlRuleBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableRuleBookTest.java
  src/test/java/seedu/address/testutil/NotificationRuleBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalRules.java
  src/test/java/seedu/address/ui/RuleListPanelTest.java
  src/test/java/systemtests/NotifyCommandSystemTest.java
Labels: type.task

#244 Amount: Disallow negative, Better print
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/coin/Amount.java
  src/main/java/seedu/address/model/coin/Price.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: category.Fix, type.bug, type.task

#250 Notification Conditions: Fix calculations, Remove useless
  src/main/java/seedu/address/logic/conditions/AmountHeldChangeCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsBoughtChangeCondition.java
  src/main/java/seedu/address/logic/conditions/DollarsSoldChangeCondition.java
  src/main/java/seedu/address/logic/conditions/MadeChangeCondition.java
  src/main/java/seedu/address/logic/conditions/WorthChangeCondition.java
  src/main/java/seedu/address/logic/parser/ConditionGenerator.java
  src/main/java/seedu/address/logic/parser/ConditionSemanticParser.java
  src/main/java/seedu/address/logic/parser/NotifyCommandParser.java
  src/main/java/seedu/address/logic/parser/TokenType.java
  src/test/java/seedu/address/logic/parser/ConditionGeneratorTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalRules.java
Labels: category.Fix, type.bug

#256 [#57] Charts Panel
  src/main/java/seedu/address/logic/commands/SyncCommand.java
  src/main/java/seedu/address/model/coin/Price.java
  src/main/java/seedu/address/ui/ChartsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ChartsPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/ChartsPanelHandle.java
  src/test/java/seedu/address/ui/ChartsPanelTest.java
Labels: category.Sync, category.UX, type.task

#263 Beautify App
  src/main/java/seedu/address/commons/events/ui/FilterChangedEvent.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/ui/CoinCard.java
  src/main/java/seedu/address/ui/IconUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/CoinListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: category.UX

#268 SyncCommand: Prevent crash when internet connection out
  src/main/java/seedu/address/logic/commands/SyncCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: category.Fix, type.bug
